server:
    port: 8080

spring:
    application:
        name: Pets API Application

    datasource:
        url: jdbc:h2:file:./db/data/petsapidb
        driver-class-name: org.h2.Driver
        username: sa
        password: admin

    h2:
        console:
            enabled: true #Enable H2 web console
            path: /h2-console #Path http://localhost:8090/h2-console

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update  # Auto-creates tables based from Entity
        show-sql: true  # Show SQL queries in logs